// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("rubrikbeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WFtz2zYTffev2MnT983InMZuPB09dOrankbTOPE09rOyAlYkahJgcLGs/voOQPBmUpQcqy8ZE5dzzgK7Z6GcwiNt56DdSovHFaE9AbDC5vRijJNhWpRWKDk/AVgLyrnxfwGcgsSC5sCUk5Z0GAOw25LmkCuZxgFN353QxOdgtaM42IWFX+MgwN2nm8uvN/Bwd315fwPXX64ebm8+31/eL758PjmJkvtifx/KjHhXSloU0gBTRaFk2Bf1Az6hyHGVEwgJmOdATyRt0G6STpi9OD1A4v+cjuE+o7AB1BpsRkEhGJJcyDQM5CqFgozBlEwCi86qsE2YBsqQ9QL9PFNyLVKn0dPBWuQ08+N+Ei08Ye78TnCGeMAU1n9KZbtgYQtkytjIFNffq0DV0zHzc2Hom//81uCoEPFuXcnw0GrG/QfXaEMDmqzTkjistoFKleRpZApmaywVoCRsMsGyVnjn7LSTUsh0RI0VBf2j5AFq6pX/pZon0kYouV9MXFinVUjncPkpSS+FONhMmCqVk37qvvvNh2IsFuW7Xp1ytDRVp2ulC7S9dfSMRelL79Klzlg4u7AZnP30/mIG78/m5x/mH86T8/Ozw043SIJNlcgUy9AXiCamNIcNmja+F0FZTM00y6VeCatRb8Pa6rQYeisI+V6Sri4KJQ8fVqM0yGx7H9U5vSCu3KF3jmr1N7G61qqPZTXzSNuN0nxaaONVzpBua8obVEX2QgFprfqGm2rlymmSG7+pdkBWMfr8Rc6FX4s5CLlWvrIZmuBfgcckdTJ0zL+rJppZM15rsvRsO4M7ZLXSIk4yIGCKD9E7LeYgdA8yhPZYA+j+nR2EXqVJbFEsV463PerKf0Kp1ZPg5MO0yNHieNu6jbOw1qqokJqtxt9Va0HI+TIsWNaQfiUjY5Te2cX80iTsSmrYl4VNbE/1fu60t77CBO6UMcInbuhJBlCTB5xBymgGSgMXqbCYK0Yok53ahDQWJaOl2FM6i7gQFte1JN9EoECWCfmydMcY9nemhqPb1w9jiQuWnTxrztmeJQVx4Ypp9tsKIqTY68jjM0fkwm6XnZbXKHDmlNDY0/dsj5F2gCB0RNF2O2EqOcK0bW4i5YI3NrfaSIkzp8+Hp17c4rX8oVSaU1Vpu9k1pXtb7V9hzb74YqFzxR5D/cRKv66/R8CrOTAWrbffPCfme3Yo82rO16zJlLbLqgPMYY258ZeGkmVK13ynTZXveJE3smC0P+zy8dgTSCeCv80TH6T47qgFBMHHXL2hK8bax6sYu3kR4OrXaRTgHxIrJ3ILSk5J6ZjBDyq5ajg91hRXjivKzYCt95aA6ffEHi2LcBIVT5O0PpnblP1YfY2ALPxjoJOovssNrKfNTT++NzMj9+vy8u138jH+rBjexpEyvTKIkSRHzTJhiVmnjxBDDw7+R0mawPMvF8uLn2eAuphBWbIZFKI0/x9KUSYpc7T+Sf82JV++Qg0UNTCSVpkZuJWT1s1gIyRXmx0i+r94flxDxBnlWGMh8u2bKSqYGKQmnqGdAaeVQDmDtSZaGT4VrSgHEnpDE+yfhLHe0BZ3p8i5JmPIDAkKZG8LsqbJUPMNamrJZuCMwzzfwu3lVVdD7SOPbkVakiXTusmf3bER2na+eQb337QtKHS9ZLottpv2GlBPNLzKhkrFj9AeOidQKl552yiVe6s1dZjuFIeHxfWQyP9rSmTHC6pFHJL5X2BHPUGPuOMID22uhxFVaFBgOWRCKZUN//91NLoO5DjnMR8sHV7We7tM0R7hyTbKW+H+GwAA//8Q65yC"
}
